---
eslint:
  stage: lint
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  when:
    - exists:
        - '**/*.{js,jsx,json,json.handlebars,toml,ts,tsx,yml}'
  allow_failure: true
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - eslint --format gitlab . # Requires eslint-formatter-gitlab
