---
stylelint:
  stage: lint
  image:
    name: megabytelabs/stylelint:slim
    entrypoint: ['']
  when:
    - exists:
        - '**/*.{css,scss}'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - stylelint "**/*.(css|scss)"
