---
stages:
  - lint
  - deploy

include:
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci-templates/-/raw/master/propagate.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci.templates/-/raw/master/shellcheck.gitlab-ci.yml
