---
stages:
  - lint
  - deploy

include:
  - local: .gitlab/ci/lint/gitlab-ci-lint.gitlab-ci.yml
  - local: .gitlab/ci/lint/prettier.gitlab-ci.yml
  - local: .gitlab/ci/lint/shellcheck.gitlab-ci.yml
  - local: .gitlab/ci/lint/yamllint.gitlab-ci.yml
  - local: .gitlab/ci/propagate/projects.gitlab-ci.yml
