---
version: '3'

tasks:
  clean:
    deps:
      - :install:software:rsync
    desc: Remove temporary folders that might conflicts with builds
    vars:
      RANDOM_STRING:
        sh: openssl rand -hex 14
    cmds:
      - mkdir -p '/tmp/{{.RANDOM_STRING}}'
      - mkdir -p '/tmp/{{.RANDOM_STRING}}-empty'
      - |
        for TMP_FILE in build test; do
          if [ -d "$TMP_FILE" ]; then
            mv "$TMP_FILE" "/tmp/{{.RANDOM_STRING}}/$TMP_FILE" 2> /dev/null
            (rsync -a --delete '/tmp/{{.RANDOM_STRING}}-empty' "/tmp/{{.RANDOM_STRING}}/$TMP_FILE" && rm -rf "/tmp/{{.RANDOM_STRING}}-$TMP_FILE") &
          fi
        done
        wait

  inspect:
    deps:
      - :common:node:dependencies:local
      - :install:npm:ts-node
    desc: Inspect the app with Chrome DevTools
    cmds:


  test:unit:
    deps:
      - :common:node:dependencies:local
      - :install:npm:ava
      - :install:npm:nyc
    desc: Run the unit tests for an NPM project
    cmds:
      - nyc --silent ava

  test:watch:
    deps:
      - :common:node:dependencies:local
      - :install:npm:ava
      - :install:npm:nyc
    desc: Run the unit tests for an NPM project in watch mode
    cmds:
      - nyc --silent ava --watch
