---
pylint:
  stage: lint
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  when:
    - exists:
        - '**/*.py'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
