---
version: '3'

tasks:
  check:package:
    interactive: true
    deps:
      - :install:software:jq
    vars:
      BLUEPRINT_REQUIRED_FIELDS: description group name overview slug subgroup
    cmds:
      - |
        ALREADY_PRESENT=true
        for ITEM in {{.BLUEPRINT_REQUIRED_FIELDS}}; do
          VALUE="$(jq --arg item "$ITEM" -r '.blueprint[$item]' package.json)"
          if [ "$VALUE" == 'null' ]; then
            echo "$ITEM blueprint data not already present"
            ALREADY_PRESENT=$ALREADY_PRESENT:$ITEM
            break
          fi
        done
        GITHUB="$(jq -r '.blueprint.repository.github' package.json)"
        if [ "$GITHUB" == 'null' ]; then
          echo "GitHub repository blueprint data is not already present"
          ALREADY_PRESENT=$ALREADY_PRESENT:repository.github
        fi
        GITLAB="$(jq -r '.blueprint.repository.gitlab' package.json)"
        if [ "$GITLAB" == 'null' ]; then
          echo "GitLab repository blueprint data is not already present"
          ALREADY_PRESENT=$ALREADY_PRESENT:repository.gitlab
        fi
        if [ ! -f 'package.json' ] || [ "$ALREADY_PRESENT" == 'false' ]; then
          node .config/scripts/prompts/package.js "$ALREADY_PRESENT"
          task boilerplate:update:taskfile
        fi

  update:taskfile:
    deps:
      - :install:software:yq
    cmds:
      - |
        GROUP="$(jq -r '.blueprint.group' package.json)"
        SUBGROUP="$(jq -r '.blueprint.subgroup' package.json)"
        TASK_GROUP="$(yq eval '.vars.REPOSITORY_TYPE' Taskfile.yml)"
        TASK_SUBGROUP="$(yq eval '.vars.REPOSITORY_SUBTYPE' Taskfile.yml)"
        if [ "$GROUP" != "$TASK_GROUP" ]; then
          yq e -i '.vars.REPOSITORY_TYPE = strenv(GROUP)' Taskfile.yml
        fi
        if [ "$SUBGROUP" != "$TASK_SUBGROUP" ]; then
          yq e -i '.vars.REPOSITORY_SUBTYPE = strenv(GROUP)' Taskfile.yml
        fi
