[flake8]
exclude = .autodoc, .cache, .common, .config, .git, .github, .gitlab, .husky, .modules, .npm, .pnpm-store, .shared, .task, .venv, .vscode, node_modules, roles, venv
ignore = E402
max-line-length = 120
