[tool.poetry]
name = "{{repository.prefix.github}}{{slug}}"
version = "{{version}}"
description = "{{description}}"
authors = ["{{author.name}} <{{author.email}}>"]
license = "{{license}}"
readme = "README.md"
homepage = "{{link.home}}"
documentation = "{{docs.link}}"
keywords = ["node", "python", "app"]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]
python = "^3.9"
blocklint = "^0.2.3"
flake8 = "^4.0.1"
{{#eq group 'packer'}}
latestos = "^0.5"
{{/eq}}
pre-commit-hooks = "^4.0.1"
proselint = "^0.12.0"
yamllint = "^1.26.3"

[tool.poetry.urls]
"Bug Tracker" = "{{repository.gitlab}}{{repository.location.issues.gitlab}}"
"GitHub" = "{{profile_link.github}}/{{profile.github}}"
"GitLab" = "https://gitlab.com/megabyte-labs"
"Megabyte Labs" = "{{link.home}}"
"Open Collective" = "{{profile_link.opencollective}}/{{profile.opencollective}}"
"Patreon" = "{{profile_link.patreon}}/{{profile.patreon}}"
"PyPi" = "{{profile_link.pypi}}/{{profile.pypi}}"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
