[tool.poetry]
name = "{{repository.prefix.github}}{{slug}}"
version = "0.1.0"
description = "{{description}}"
authors = ["{{author.name}} <{{author.email}}>"]
license = "{{license}}"
readme = "README.md"
homepage = "{{link.home}}"
documentation = "{{docs.link}}"
keywords = ["node", "python", "app"]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
blocklint = "^0.2.3"
pre-commit-hooks = "^4.0.1"
proselint = "^0.12.0"
yamllint = "^1.26.3"

[tool.poetry.urls]
"Bug Tracker" = "{{repository.gitlab}}{{repository.location.issues.gitlab}}"
"Megabyte Labs" = "{{link.home}}"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
