---
version: '3'

tasks:
  common:
    cmds:
      - task: :upstream:common:clone
      - task: :upstream:common:copy
      - task: :upstream:common:merge
      - task: :upstream:common:clean
      - task: :upstream:common:template
      - task: :fix:eslint

  project:
    cmds:
      - task: :upstream:project:clone
