lane :deploy do
    ionic(
    platform: 'android',
    keystore_path: ENV['CORDOVA_ANDROID_KEYSTORE_PATH'],
    keystore_alias: ENV['CORDOVA_ANDROID_KEYSTORE_ALIAS'],
    keystore_password: ENV['CORDOVA_ANDROID_KEYSTORE_PASSWORD']
    )
    supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
end

